use_frameworks!

platform :ios, '12.0'

target 'YYWebImageFork_Example' do
  pod 'YYWebImageFork', :path => '../'

  pod 'YYImageWebp'
  pod 'YYCache'
  
  target 'YYWebImageFork_Tests' do
    inherit! :search_paths

    
  end
end
